from selenium.webdriver.common.by import By

search_in = (By.CSS_SELECTOR,"body > div.modalBluring > div > div.topMenu__wrapper.topMenu_experimentFixedMenu > div > div.toolbox > div > div > input")
search_sel = (By.CSS_SELECTOR, "#ui-id-1")
form_menu = (By.CSS_SELECTOR, "#contentSelectorSelect-button > span.ui-selectmenu-icon.ui-icon.ui-icon-triangle-1-s")
gen_menu = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.main-container_experimentFixedMenu > div.table-row > div.table-cell.centerContent > div > div.topFilterRow > div.genreSelector.selectBox")
coun_menu = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.main-container_experimentFixedMenu > div.table-row > div.table-cell.centerContent > div > div.topFilterRow > div.countrySelector.selectBox")
vod_menu = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.main-container_experimentFixedMenu > div.table-row > div.table-cell.centerContent > div > div.topFilterRow > div.vodSelector.selectBox")
f_ui_menu_f = (By.CSS_SELECTOR, "#contentSelectorSelect-menu > li:nth-child(1)")
f_ui_menu_s = (By.CSS_SELECTOR, "#contentSelectorSelect-menu > li:nth-child(2)")
f_ui_menu_m = (By.CSS_SELECTOR, "#contentSelectorSelect-menu > li:nth-child(3)")
el_fil_m = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.main-container_experimentFixedMenu > div.table-row > div.table-cell.centerContent > div > ul.selectResult.selectResultcontentSelector > li:nth-child(1)")
el_fil_s = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.main-container_experimentFixedMenu > div.table-row > div.table-cell.centerContent > div > ul.selectResult.selectResultcontentSelector > li:nth-child(2)")
el_fil_a = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.main-container_experimentFixedMenu > div.table-row > div.table-cell.centerContent > div > ul.selectResult.selectResultcontentSelector > li:nth-child(3)")
gen_act = (By.CSS_SELECTOR, "#genreSelectorSelect-button")
coun_act = (By.CSS_SELECTOR, "#countrySelectorSelect-button")
vod_act = (By.CSS_SELECTOR, "#vodSelectorSelect-button")
fil_ser = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.table-single-cell.main-container_experimentFixedMenu > div.table-row.table-single-cell > div > div.trailers__filters.scroll-menu__wrap > div > label.iocheckbox.trailers__iocheckbox_serial.iocheckboxChecked")
fil_ser_off = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.table-single-cell.main-container_experimentFixedMenu > div.table-row.table-single-cell > div > div.trailers__filters.scroll-menu__wrap > div > label.iocheckbox.trailers__iocheckbox_serial")
fil_lang = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.table-single-cell.main-container_experimentFixedMenu > div.table-row.table-single-cell > div > div.trailers__filters.scroll-menu__wrap > div > label:nth-child(2)")
fil_lang_off = (By.CSS_SELECTOR, "body > div.modalBluring > div > div.table.main-table_content.main-table.table-single-cell.main-container_experimentFixedMenu > div.table-row.table-single-cell > div > div.trailers__filters.scroll-menu__wrap > div > label:nth-child(2) > input[type=checkbox]")
gen_prem = (By.CSS_SELECTOR, "#genreSelectorSelect-button")
coun_prem = (By.CSS_SELECTOR, "#countrySelectorSelect-button")
years_prem = (By.CSS_SELECTOR, "#yearSelectorSelect-button")
